### ISSUE TITLE
Pets don't interact with application windows with multiple monitors

### ISSUE THREAD

**Issue by TheMadBug** [curzel-it/pet-therapy#13]
For clarification, I have default settings of "interact with desktop" turned on.

When I have two monitors plugged in, pets on either monitor will fall through any windows and always hit the very bottom of the screen.
If I set it up so the pet is only on one monitor (but a 2nd monitor is still plugged in) the same happens.
If I unplug the 2nd monitor, it works a treat, using the tops of windows as a walking platform.

Running
Apple M1 Pro
On macOS 13.2.1

Let me know if there's any more details you want. I could also have a go at running the project in XCode myself and debugging if you point me in the right direction. Thanks for the fun app!

**Comment by curzel-it** [comment]
Hello!
The option is not supported on multiple monitors, so what you have is the expected behavior, at least for the moment!
Should not be super hard to add, I might add it soon ;)
Thanks for reaching out, and for liking the app!

**Comment by TheMadBug** [comment]
.... and now I read the help for the interaction button that explained that already. Sorry about that.

**Comment by curzel-it** [comment]
No worries, it's still something I need to add so thanks for pinging me ;)

**Comment by curzel-it** [comment]
@TheMadBug 
I just merged [this one](https://github.com/curzel-it/pet-therapy/pull/15), which makes desktop interactions available when there's multiple monitors, but still only for the main screen.
There's a quirk in how the coordinate system of Screens vs Windows/Views work, which is a bit different...
I'll fix that too eventually :D
