### ISSUE TITLE
Provide a new pet

### ISSUE THREAD

**Issue by Chuck-Ray** [curzel-it/pet-therapy#20]
Hello, I want to add a role  of Genshin ———— keli
https://github.com/Chuck-Ray/pet-therapy-role

![image](https://user-images.githubusercontent.com/63182083/221105136-7d48d7aa-4475-4d41-8497-3278cb0bceaf.png)

<img width="63" alt="image" src="https://user-images.githubusercontent.com/63182083/221104190-592d7bbb-dfcc-4536-9944-bb166a0e5a13.png">

![image](https://user-images.githubusercontent.com/63182083/221104246-406ac77e-3a70-4cdc-9619-029a82b3448b.png)

**Comment by curzel-it** [comment]
Haha I love Keli!
I can definately add her to the app!
Do you want to be listed in the contributors section of the app? 
If so, i need any name you want and optionally an avatar and a link

**Comment by chuck-san** [comment]
wow, thank you. I have contacted the author of the assets - catKnow. And we plan to make more characters of Genshin, We will provide you with the name and avatar after we finish  In the next few weeks :)

**Comment by Chuck-Ray** [comment]
Hi, I have updated three characters in the[ repo](https://github.com/Chuck-Ray/pet-therapy-role). Now there are three characters: Klee, Keqing, and Raiden Yin from Genshin Impact. Thanks to the resource author providing more action images, their movements are now more diverse.

However, there is an issue with Klee's package in the current version. After walking for a while, it will freeze for about two minutes. I tried deleting the walking animation to three images, but it still gets stuck. **Could you please take a look and help me out? Then I will update Klee's resource package again**.

Additionally, please add **catknow** to the list of contributors. his avatar is this: 

![猫知道 logo](https://user-images.githubusercontent.com/63182083/228447068-a4873b9a-ccc9-44cd-bb0e-02f18ae2adb7.png) 

 and his link is  https://space.bilibili.com/889964

Finally, please add the Chinese translation of "Genshin" to "原神" in the tags. and the Chinese translation of "klee" to "可莉" , "keqing" to "刻晴" ,"Raiden" to "雷电"

**Comment by Chuck-Ray** [comment]
Hi, I have updated three characters in the[ repo](https://github.com/Chuck-Ray/pet-therapy-role). Now there are three characters: Klee, Keqing, and Raiden Yin from Genshin Impact. Thanks to the resource author providing more action images, their movements are now more diverse.

However, there is an issue with Klee's package in the current version. After walking for a while, it will freeze for about two minutes. I tried deleting the walking animation to three images, but it still gets stuck. **Could you please take a look and help me out? Then I will update Klee's resource package again**.

Additionally, please add **catknow** to the list of contributors. his avatar is this: 

![猫知道 logo](https://user-images.githubusercontent.com/63182083/228447068-a4873b9a-ccc9-44cd-bb0e-02f18ae2adb7.png) 

 and his link is  https://space.bilibili.com/889964

Finally, please add the Chinese translation of "Genshin" to "原神" in the tags. and the Chinese translation of "klee" to "可莉" , "keqing" to "刻晴" ,"Raiden" to "雷电"

**Comment by curzel-it** [comment]
Terrific work!
Will do with the next update, I'll keep you posted!

**Comment by curzel-it** [comment]
It took me a while, but i've finally merged and sent an update to Apple, should be out in a couple of days!
Also implemented a "scale" property for pets, so that Raiden (48x48) can be the same size as Klee and Keqing (32x32).
You're also been added to contributors, sorry again for the delay!

**Comment by curzel-it** [comment]
Version 2.46 is out now with your character, thanks again!
