### ISSUE TITLE
UFO character not available

### ISSUE THREAD

**Issue by Alien-Sketch** [curzel-it/pet-therapy#4]
The ufo one advertised isn't in the mac app :(

Also, most other designs available are ugly.

But other than that hell yeah shimejis lesgoooooo

**Comment by curzel-it** [comment]
Hello!
> The ufo one advertised isn't in the mac app :(
Wasn't satisfied with some animations, but it's coming back with the next update, so matter of days/weeks!

> hell yeah shimejis lesgoooooo
I am open to ideas, post any link/images for inspiration!

**Comment by Alien-Sketch** [comment]
Sorry if I was a bit harsh before, I've actually made pixel art in the past and I would be very interested in contributing to the project.

**Comment by curzel-it** [comment]
No worries... 

So, if you want to **contribute as a designer**, we can do that two ways:

**Option 1**
Just put togheter any design, pixel art or not, and either send them to me or open a pull request.
**I'll make sure your pets are available when building from source, but NOT on the App Store.**

**Option 2**
Contact me on my profile email, attach some sketchs of your idea, and we'll work something out!

If you want to **contribute as a dev**, well, let me know in my email 😄

**Comment by curzel-it** [comment]
v2.8 out now, with the UFO!
