### ISSUE TITLE
Change pet direction when collides with other pets

### ISSUE THREAD

**Issue by GabM3** [curzel-it/pet-therapy#43]
It could be fun if whenever a pet collide with another one, both will change directions

**Comment by curzel-it** [comment]
Hi Gabriele, this was actually the behavior up to version ~2.10 or so!
The reason for the removal is the following:
While cool, most of our users use 13" macbooks, mostly with no external displays, and tend to have 4-5 pets on screen at the same time.
I discussed with the users on our discord at the time and we figure out it was best to avoid detecting those collisions...

With that said, we could still make this a species-specific behavior, or make it a setting.
Just need to change the "valid collisions" filter used in [BouncingOffLateralCollisions](https://github.com/curzel-it/pet-therapy/blob/6440e8d4f9153a09312923eac41270b914beddb1/Sources/macOS/Packages/Yage/Sources/Yage/Capabilities/BounceOnLateralCollisions.swift) capability

**Comment by GabM3** [comment]
what about adding a new setting with turning it on/off like it is done for gravity?

**Comment by curzel-it** [comment]
Ok! I'll push later today!

**Comment by curzel-it** [comment]
Release in v2.47, you should receive an update via App Store soon ;)
