### ISSUE TITLE
Grumpy Cat doesn't fall while sleeping.

### ISSUE THREAD

**Issue by egementrk** [curzel-it/pet-therapy#5]
while Enable Gravity on
<img src="https://user-images.githubusercontent.com/55029049/198849352-4950604b-cd50-45e2-a287-4f02a762d0eb.png" width="412" height="152">
MacBook Air M1
macOS Ventura

**Comment by curzel-it** [comment]
Hi @egementrk, thanks for reporting!
By design, gravity is disabled while any animation (or action if you will) is taking place.
There's no strong reason for this that I can remember, so this might be very quick to fix!

**Comment by egementrk** [comment]
It seems solved with your last commit

**Comment by curzel-it** [comment]
Yes indeed, thanks for taking the time to verify!
I was waiting for App Store release to happen, but seems Apple is a bit behind the usual schedule, maybe because of halloween and Ventura release.
